# Generated by Django 3.2.9 on 2021-12-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_wesbite',
            new_name='social_website',
        ),
    ]
